name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar archivos en el workspace
        run: ls -la $GITHUB_WORKSPACE

      - name: Verificar versión de Docker Compose
        run: docker compose version || docker-compose version

      - name: Ejecutar Docker Compose
        run: docker compose -f $GITHUB_WORKSPACE/docker-compose.yml up --build -d
