# This is a basic workflow to help you get started with Actions

name: CI

# Controla cuándo se ejecutará el flujo de trabajo
on:
  # Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama "main".
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo.
jobs:
  # Este flujo de trabajo contiene un único trabajo llamado "construir"
  construir:
    env:
      ENVIRONMENT: production
      BD_HOST: localhost
      BD_USER: cesar
      BD_PASSWORD: 123456
      BD_HOST_SECRET: ${{secrets.BD_HOST_SECRET}}
      BD_PASSWORD_SECRET: ${{secrets.BD_PASSWORD_SECRET}}
      BD_USER_SECRET: ${{secrets.BD_USER_SECRET}}
    # El tipo de corredor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      # Ejemplo de job 1
      - name: Paso 1
        run: echo ejecución paso 1

      # Ejemplo de job 2
      - name: Paso 2
        run: |
          echo ejecución paso 2,
          echo test, ejecución paso 2 test.
      
      # Ejemplo de job 3
      - name: Paso 3 - mostrando variables de entorno
        run: |
          echo "BD_HOST: ${{env.BD_HOST}}",
          echo "BD_USER: ${{env.BD_USER}}",
          echo "BD_PASSWORD: ${{env.BD_PASSWORD}}"
      

      # Ejemplo de job 4
      - name: Paso 4 - condición
        if: ${{env.ENVIRONMENT=='production'}}
        run: |
          echo "BD_HOST: ${{env.BD_HOST}}",
          echo "BD_USER: ${{env.BD_USER}}",
          echo "BD_PASSWORD: ${{env.BD_PASSWORD}}"

      # Ejemplo de job 5 (toJson(github.event))
      - name: Paso 5 - variables predefinidas 
        run: |
          echo "Evento: ${{github.event}}",
          echo "GITHUB_ACTION_REPOSITORY: ${{github.GITHUB_ACTION_REPOSITORY}}",
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH",
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY",
          echo "GITHUB_ACTOR: $GITHUB_ACTOR",
    
     # Ejemplo de job 6
      - name: Paso 6 - mostrando secretos
        run: |
          echo "BD_HOST_SECRET: ${{env.BD_HOST_SECRET}}",
          echo "BD_USER_SECRET: ${{env.BD_USER_SECRET}}",
          echo "BD_PASSWORD: ${{env.BD_PASSWORD}}"
      
      - name: Paso 7 - mostrando secretos condicionados
        if: ${{env.ENVIRONMENT_SECRET=='local-secreto'}}
        run: |
          echo "se muestra ENVIRONMENT_SECRET"
